version: "3.9"

services:
  app:
    container_name: app
    image: app:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      app-network:
        ipv4_address: 172.21.0.10

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      app-network:
        ipv4_address: 172.21.0.11

networks:
  app-network:
    name: app-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1